alertageral/alerta/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('alerta.views',
    (r'todosalertas', 'todosalertas'),
    (r'recentes_alertas', 'recentes_alertas'),
    (r'cadastro', 'cadastro'),
    (r'recupera_senha', 'recupera_senha'),
    (r'cadastrar_alerta', 'cadastrar_alerta'),
    (r'comentarios/(?P<alerta_id>\d+)$', 'comentarios'),
    (r'validar_responder_alerta/(?P<alerta_id>\d+)$', 'validar_responder_alerta'),
    (r'responder_alerta/(?P<alerta_id>\d+)$', 'responder_alerta'),
)

alertageral/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import *
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import os

admin.autodiscover()
admin.autodiscover()

handler500 = 'django.views.defaults.server_error'
handler404 = 'django.views.defaults.page_not_found'

urlpatterns = patterns('',
    
    (r'^admin/', include(admin.site.urls)),
    (r'^media/(.*)$', 'django.views.static.serve',
     {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(.*)$', 'django.views.static.serve',
     {'document_root': settings.STATIC_ROOT}),
    (r'^accounts/login/$', 'django.contrib.auth.views.login',
     {'template_name': 'templates/login.html'}),
    (r'^admin/logout/$', 'django.contrib.auth.views.logout',
     {'next_page': '/'}),
    (r'^logout/', 'django.contrib.auth.views.logout',
     {'next_page': '/'})
)

# Include de cada app instalada
for app in settings.INSTALLED_APPS:
    if not app.startswith('django.'):
        if os.path.exists(os.path.join(settings.PROJECT_PATH, '%s/urls.py' % (app))):
            urlpatterns += patterns('',
                (r'^%s/' % (app), include('%s.urls' % (app)) ),
            )

urlpatterns += patterns('views',
    # Geral
    (r'^$', 'index'),
)

alertageral/alerta/models.py
from django.db import models
from django.contrib.auth.models import User
from comum.views import enviar_email
from django.core.exceptions import ValidationError

class Instituicao(models.Model):
    nome = models.CharField(max_length=50)
    responsavel = models.CharField(max_length=50)
    e_mail = models.EmailField(max_length=50, verbose_name='E-mail')
    telefone = models.CharField(max_length=13, help_text='Ex. (xx)xxxx-xxxx')

    class Meta:
        verbose_name_plural = 'Instituicoes'

    def __unicode__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if (Instituicao.objects.count() > 0 and self.id != Instituicao.objects.get().id):
            raise ValidationError("Limitado a 1 instancia")
        super(Instituicao, self).save(*args, **kwargs)

        
class TipoUnidade(models.Model):
    descricao = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Tipos Unidades'
        
    def __unicode__(self):
        return self.descricao

class Unidade(models.Model):
    nome = models.CharField(max_length=50)
    responsavel = models.CharField(max_length=50)
    e_mail = models.EmailField(max_length=50, verbose_name='E-mail')
    telefone = models.CharField(max_length=13, help_text='ex. (xx)xxxx-xxxx')
    instituicao = models.ForeignKey(Instituicao)
    tipo = models.ForeignKey(TipoUnidade)

    def __unicode__(self):
        return self.nome

class Departamento(models.Model):
    nome = models.CharField(max_length=50)
    responsavel = models.CharField(max_length=50)
    e_mail = models.EmailField(max_length=50, verbose_name='E-mail')
    telefone = models.CharField(max_length=13, help_text='ex. (xx)xxxx-xxxx')
    telefone = models.CharField(max_length=13, help_text='ex. (xx)xxxx-xxxx')
    unidade = models.ForeignKey(Unidade)
    chave = models.CharField(max_length=20, help_text='Chave de acesso para responder alerta max 20 caracteres')

    def __unicode__(self):
        return self.nome

class Assunto(models.Model):
    nome = models.CharField(max_length=50)
    departamento = models.ForeignKey(Departamento)

    def __unicode__(self):
        return self.nome

class Usuario(User):
    unidade = models.ForeignKey(Unidade)
    cpf = models.CharField(max_length=14, unique=True)
    apelido = models.CharField(max_length=20)
    moderador = models.BooleanField(default=False)
    telefone = models.CharField(max_length=13, help_text='ex. (xx)xxxx-xxxx', blank=True, null=True)
    
    def __init__(self, *args, **kwargs):
        super(Usuario, self).__init__(*args, **kwargs)
        self.can_delete = False
        
    def save(self, *args, **kwargs):
        # do anything you need before saving
        super(Usuario, self).save(*args, **kwargs)
        us = Usuario.objects.get(id=self.pk)
        us.set_password(us.password)
        u = Usuario.objects.filter(id=self.pk).update(password=us.password)
    def __unicode__(self):
        return self.cpf

class Alerta(models.Model):
    usuario = models.ForeignKey(User)
    data_criacao = models.DateField()
    assunto = models.ForeignKey(Assunto)
    # unidade = models.ForeignKey(Unidade) # Relacionado com assunto
    # departamento = models.ForeignKey(Departamento) # Relacionado com assunto
    imagem = models.ImageField('Imagem', upload_to='imagens', blank=True)
    texto = models.TextField()
    anonimo = models.BooleanField(default=False)
    ativo = models.BooleanField(default=True)
    
    def save(self, *args, **kwargs):
        # do anything you need before saving
        if self.pk is None:
            tipo = 'alerta'
            try:
                enviar_email('Novo Alerta', 'alertageral@gmail.com', self.usuario.email, self.assunto, tipo)
            except:
                pass
        super(Alerta, self).save(*args, **kwargs)
        
    def __unicode__(self):
        return '%s - %s' %(self.usuario, self.assunto.nome)
        
class Comentario(models.Model):
    usuario = models.ForeignKey(User)
    alerta = models.ForeignKey(Alerta)
    data_criacao = models.DateField()
    texto = models.TextField()

    def __unicode__(self):
        return '%s - %s' %(self.usuario, self.texto)

class Resposta(models.Model):
    usuario = models.ForeignKey(User)
    alerta = models.ForeignKey(Alerta)
    data_criacao = models.DateField()
    texto = models.TextField()

    def __unicode__(self):
        return '%s - %s' %(self.usuario, self.texto)

alertageral/alerta/forms.py
# -*- coding: utf-8 -*-

from djtools import forms
from djtools.formwidgets import *
from alerta.models import *

class AlertaForm(forms.ModelForm):
    class Meta:
        model = Alerta
        fields = ['imagem']
        
        imagem = forms.ImageField(required=True)

    # def clean_cpf(self):
        # cpf = self.cleaned_data['cpf']
        # if len(cpf) < 14:
            # raise forms.ValidationError(u'CPF inválido formato deve ser XXX.XXX.XXX-XX')
            # d2 = 11-d2
        # if (cpf_array[9] != d1) | (cpf_array[10] != d2):
            # raise forms.ValidationError(u'CPF inválido - Digito verificador inválido')
        # return self.cleaned_data['cpf']

alertageral/alerta/views.py
# -*- coding: utf-8 -*-

import django.shortcuts
from django.contrib.auth.decorators import login_required, permission_required
from djtools.utils import rtr, httprr, str_to_dateBR, group_required, \
    user_has_profile, user_has_one_of_perms, get_rss_links, to_ascii
from django.template import RequestContext
from alerta.forms import *
from alerta.models import *
from django.db.models import Count, Sum
from djtools import db
from comum.views import enviar_email
import random, datetime
from alerta.forms import *
from django.contrib.auth.models import User

@login_required
def cadastrar_alerta(request):
    if request.method == "POST":
        form = AlertaForm(request.POST)
        if form.is_valid():
           # try except disponibilizado para permitir que alertas sem imagens e marcacao
		   # funcione
           try:
               img = request.FILES['imagem']
           except:
               img = 'imagens/padrao.jpg'
           try:
               anonimo = request.POST['anonimo']
               anonimo = True
           except:
		       anonimo = False
           ass = Assunto.objects.get(id=int(request.POST['assunto']))
           comentario = request.POST['comentario']
           usuario = request.user
           alerta = Alerta.objects.create(usuario=usuario, data_criacao=datetime.date.today(),\
           assunto=ass, imagem=img, texto=comentario, anonimo=anonimo)
           tipo = 'alerta'
           inf = [comentario]
           e_mail1 = usuario.email
           e_mail2 = ass.departamento.e_mail
           enviar_email('Novo Alerta Cadastrado', 'alertageral@gmail.com', e_mail2, inf, tipo)
           enviar_email('Novo Alerta Cadastrado', 'alertageral@gmail.com', e_mail1, inf, tipo)
        return django.shortcuts.render(request, 'confirmaenviaalerta.html',locals())
        
    else:
        form = AlertaForm()
        # Se for super usuário todos os alertas são carregados
    if request.user.is_superuser:
        assuntos = Assunto.objects.all()
        alertas = Alerta.objects.filter(ativo=True).order_by('-id')
    else:
        usuario = Usuario.objects.get(username=request.user.username)
        unidade = usuario.unidade
        assuntos = Assunto.objects.filter(departamento__unidade=unidade)
        alertas = Alerta.objects.filter(usuario=usuario,ativo=True).order_by('-id')
    return django.shortcuts.render(request, 'cadastroalerta.html',locals())

@login_required
def comentarios(request, alerta_id):
    if request.method == "POST":
       alerta = Alerta.objects.get(id=int(alerta_id))
       coment = request.POST['comentario']
       comentario = Comentario.objects.create(usuario=request.user, alerta=alerta, data_criacao=datetime.date.today(),\
       texto=coment)
       alerta = Alerta.objects.get(id=alerta_id)
       comentarios = Comentario.objects.filter(alerta=alerta).order_by('-id')
       respostas = Resposta.objects.filter(alerta=alerta).order_by('-id')
       return django.shortcuts.render(request, 'comentarios.html',locals())
    else:
        alerta = Alerta.objects.get(id=alerta_id)
        comentarios = Comentario.objects.filter(alerta=alerta).order_by('-id')
        respostas = Resposta.objects.filter(alerta=alerta).order_by('-id')
    return django.shortcuts.render(request, 'comentarios.html',locals())

@login_required
def validar_responder_alerta(request, alerta_id):
    if request.method == "POST":
       alerta = Alerta.objects.get(id=alerta_id)
       try:
	       chave = request.POST['chave']
       except:
           return django.shortcuts.render(request, 'loginchave.html',locals())
       chave_departamento = alerta.assunto.departamento.chave
       if chave == chave_departamento:
           # a seguranca de poder responder deve ser melhorada
           # nao houve tempo habil para desenvolver esta funcao
		   # o controle de permissoes de usuario deve ser mais seguro
		   # mas o requisito inicial preve essa chave de permissao
           pode_responder = '8i234sdcskckishbHBVTVy@734794hb@jhbi#$bibyibiuyB@iybUI#ibiyby6382'
           return django.shortcuts.render(request, 'respostas.html',locals())
       else:
           pode_responder = '8i234sdcskckishbHBVTVy@734794hb@jhdi#$bibyibiuyB@iybUI#ibiyby6382'
           erro = 'Chave incorreta'
           return django.shortcuts.render(request, 'loginchave.html',locals())
    return django.shortcuts.render(request, 'comentarios.html',locals())

@login_required
def responder_alerta(request, alerta_id):
    if request.method == "POST":
       if request.POST['texto'] == '8i234sdcskckishbHBVTVy@734794hb@jhbi#$bibyibiuyB@iybUI#ibiyby6382':
           alerta = Alerta.objects.get(id=int(alerta_id))
           resposta = request.POST['resposta']
           res = Resposta.objects.create(usuario=request.user,alerta=alerta,data_criacao=datetime.date.today(),texto=resposta)
           respostas = Resposta.objects.filter(alerta=alerta).order_by('-id')
           mensagem = 'Resposta cadastrada com sucesso'
           return django.shortcuts.render(request, 'respostas.html',locals())
       else:
           pass
    return django.shortcuts.render(request, 'comentarios.html',locals())

def todosalertas(request):
    alertas = Alerta.objects.filter(ativo=True).order_by('-id')

    return django.shortcuts.render(request, 'todosalertas.html',locals())
    
def recentes_alertas(request):
    alertas = Alerta.objects.filter(ativo=True).order_by('-id')[:12]
    
    return django.shortcuts.render(request, 'recentesalertas.html',locals())

def cadastro(request):
    if request.method == "POST":
        un = Unidade.objects.get(id=int(request.POST['unidade']))
        nome = str(request.POST['nome'])
        apelido = str(request.POST['apelido'])
        cpf = str(request.POST['cpf'])
        mail = str(request.POST['mail'])
        telefone = str(request.POST['telefone'])
        senha = str(request.POST['senha'])
        us = Usuario.objects.create(cpf=cpf,apelido=apelido,telefone=telefone,\
        password=senha,username=cpf, first_name=nome,email=mail, unidade=un)
        us.set_password(us.password)
        u = Usuario.objects.filter(id=us.pk).update(password=us.password)
        inf = [us.username,senha]
        tipo = 'cadastro'
        try:
            enviar_email('Cadastro Alerta Geral', 'alertageral@gmail.com', us.email, inf, tipo)
        except:
            mensagem = 'O cadastro foi realizado mas houve falha no envio do e-mail, tente acessar o sistema'
            return django.shortcuts.render(request, 'confirmacadastro.html',locals())
        return django.shortcuts.render(request, 'confirmacadastro.html',locals())
    else:
        unidades = Unidade.objects.all()
        return django.shortcuts.render(request, 'cadastro.html',locals())

def cria_senha(tamanho):
        caracters = '0123456789abcdefghijlmnopqrstuwvxz@#&'
        senha = ''
        for char in xrange(tamanho):
                senha += random.choice(caracters)
        return  senha

def recupera_senha(request):
    if request.method == "POST":
        try:
            senha = cria_senha(6)
            us = Usuario.objects.filter(email=request.POST['mail'])
            u = us[0]
            u.set_password(senha)
            us1 = Usuario.objects.filter(id=u.pk).update(password=u.password)
            tipo = 'senha'
            inf = [u.username,senha]
            enviar_email('Recupera Senha Alerta Geral', 'alertageral@gmail.com', us[0].email, inf, tipo)
            return django.shortcuts.render(request, 'confirmarecuperasenha.html',locals())
        except:
            mensagem = 'Nao foi possivel enviar o e-mail contate o administrador do sistema exemplo@exemplo.com'
            return django.shortcuts.render(request, 'recuperasenha.html',locals())
    else:
        return django.shortcuts.render(request, 'recuperasenha.html',locals())

alertageral/alerta/templates/cadastro.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sistema Alerta Geral</title>
<!--<link href="css/estilos.css" rel="stylesheet" type="text/css" />-->
<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body bgcolor="#dfeae2">
<div id="conteudo_principal">
<div id="banner"> </div>
  <div id="centro">
  <div id="centroform">
  {% if mensagem %}
	<font color=red>{{ mensagem }}</font>
  {% endif %}
<form action="/alerta/cadastro/" name="cadastro" id="cadastro_form" method="POST">
    {% csrf_token %}
    <br/>
    <div class="control-group">
    <div class="controls">
    <div class="input-prepend">
    <span class="add-on"><i class="icon-user"></i></span>
    <input class="span2" name="nome" id="inputIcon" type="text" placeholder="Nome">
    <br>
    <span class="add-on"><i class="icon-tag"></i></span>
    <input class="span2" name="apelido" id="inputIcon" type="text" placeholder="Apelido">
    <br>
    <span class="add-on"><i class="icon-file"></i></span>
    <input class="span2" name="cpf" id="inputIcon" type="text" placeholder="cpf">
    <br>
    <span class="add-on"><i class="icon-envelope"></i></span>
    <input class="span2" name="mail" id="inputIcon" type="text" placeholder="E-mail">
    <br>
    <span class="add-on"><i class="icon-volume-up"></i></span>
    <input class="span2" name="telefone" id="inputIcon" type="text" placeholder="Telefone">
    <br>
    <span class="add-on"><i class="icon-lock"></i></span>
    <input class="span2" name="senha" id="inputIcon" type="password" placeholder="Senha">
    <br>
    <span class="add-on"><i class="icon-home"></i></span>
        <select name="unidade" placeholder="Unidade">
            {% for u in unidades %}
                <option value="{{ u.id }}">{{ u.nome }}</option>
            {% endfor%}
        </select>
    </div>
    </div>
    </div>
    <br />
    <a href="cadastro.html">
    <button class="btn btn-danger" type="submit">Criar conta</button>
    </a>    <a href="/">
    <button class="btn btn-link" type="button">Voltar atrás</button>
</form>    
    </a>  </div> 
  </div>

  <div id="rodape">
  <br />
  <br />
  <center><h1><font face="Segoe Script">Novo no Alerta Geral?</font></h1></center>
  <center>
    <a href="cadastro.html">
    <button class="btn btn-danger" type="button">   Clique aqui para realizar o cadastro!   </button>
    </a>
  </center>
  </div>
</div>
</div>
<script src="http://code.jquery.com/jquery-latest.js"></script><script src="js/bootstrap.min.js"></script>
</body>
</html>

alertageral/alerta/templates/cadastroalerta.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sistema Alerta Geral</title>
<!--<link href="css/estilos.css" rel="stylesheet" type="text/css" />-->
<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body bgcolor="#dfeae2">
<div id="conteudo_principal">

<div id="banner"><a href=/> </a><div align="right">
<a href="/">
<button class="btn btn-link" type="button">Inicio</button>
</a><a href="/logout/">
<button class="btn btn-link" type="button">Logout</button>
</a><a href="/alerta/recupera_senha/">
<button class="btn btn-link" type="button">Alterar Senha</button>
</a><a href="/admin/">
<button class="btn btn-link" type="button">Administração</button>
</a></div> </div>
  <div id="centro">
  <div id="centroform">
    <br />
    <div class="control-group">
    <div class="controls">
    <div class="input-prepend">
    </div>
    </div>
    </div>
    <div class="control-group">
    <div class="controls">
    <div class="input-prepend">
<form action="/alerta/cadastrar_alerta/" name="cadastrar_alerta" id="cadastrar_alerta_form" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <span class="add-on"><i class="icon-list-alt"></i></span    >
        <select name="assunto">
            {% for a in assuntos %}
                <option value="{{ a.id }}">{{ a.nome }}</option>
            {% endfor%}
        </select>
    <br>
    <br>
   <TEXTAREA NAME="comentario" COLS=45 ROWS=3 style="width:237px; height:50px;"></TEXTAREA>
   <br>
    {{ form }}
<!--     <span class="add-on"><i class="icon-camera"></i>Fotos ou Vídeos</span>
   <br />
   <input id="id_imagem" type="file" name="imagem"> -->
   <br />
   <br />
    <a href="cadastrar_alerta">
    <button class="btn btn-danger" type="submit"> Enviar    Alerta </button>
    </a>
	<br>
	<br>
<label><b>Marcar como anônima</b></label>
<input type="checkbox" name="anonimo" value="anonimo"> </input>
</form>
    </div>
    </div>
    </div>
  </div> 
  </div> 
  <div id="rodape2">
  <br />
  <br />
  <div id="tabtable">
			<div class="tabbable" id="tabs-362792">
				<ul class="nav nav-tabs">
					<li class="active">
						<a href="#panel-582106" data-toggle="tab" style="font-family:digital_dreamregular"><h6>Meus Alertas</h6></a>
					</li>
<!-- 					<li>
						<a href=cadastroalerta_com.html style=font-family: 'digital_dreamregular'><h6>Meus Comentários</h6></a>
					</li> -->
				</ul>
			</div>
		</div>
	
<div class="container" style="background-color:#FFF" id=container>

	<div class="row clearfix" >
		
		
		<!-- Todos Alertas -->
		<br clear="all"/>
            {% for a in alertas %}
            <div id="imagem_alertas1">
                <table>
				<tr>
					<td><img alt="{{ a.imagem }}" width=120  height=120 {% ifequal a.imagem "" %}
                    src="/media/imagem/imagemAlerta.png" 
                    {% else %}
                    src="/media/{{ a.imagem }}"
                    {% endifequal %}class="img-circle" ></td>
                    <!-- <td><img alt="{{ a.imagem }}" width=120 height=120 src="/media/{{ a.imagem }}" class="img-circle" ></td> -->
					<td width=500 align="right"><blockquote><font color="#FF0000">Desativar</font>
						<div class="well well-small"   style="color:black">
							<p>
								<a href=/alerta/comentarios/{{ a.id }} style="color:black">{{ a.texto }}</a>
							</p> 
							<small>
                                {{ a.data_criacao }}
								<br>
								
								{% if a.anonimo == True %}
								    Anônimo
								{% else %}
									{{ a.usuario.username }}
								{% endif %}
								
							</small>
						</div>
						</blockquote></td>     
				</tr>
                </table>
            </div>	
            {% endfor %}
		
	</div>
    <br>
    <br>
    <br>
</div>
</div>
</div>
</div>
<script src="http://code.jquery.com/jquery-latest.js"></script><script src="js/bootstrap.min.js"></script>
</body>
</html>

alertageral/alerta/templates/confirmacadastro.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sistema Alerta Geral</title>
<!--<link href="css/estilos.css" rel="stylesheet" type="text/css" />-->
<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body bgcolor="#dfeae2">
<div id="conteudo_principal">
<div id="banner"> </div>
  <div id="centro">
  <div id="centroform">
    <br />
    <br />
   <h5><font face="Arial, Helvetica, sans-serif"><b>Obrigado por criar sua conta!</b></font></h1>
    <br />
    <h6><font face="Arial, Helvetica, sans-serif">Ao efetuar o login no Alerta Geral, utilize o endereço de e-mail e a senha criada no cadastro.  </font></h1>
    <br />
    <br />
   <a href="login.html">
    <button class="btn btn-danger" type="button">   Volta a tela de login   </button>
    </a>    <a href="login.html">
    </a>  </div> 
  </div> 
  <div id="rodape">
  <br />
  <br />
  <center><h1><font face="Segoe Script">Novo no Alerta Geral?</font></h1></center>
  <center>
    <a href="cadastro.html">
    <button class="btn btn-danger" type="button">   Clique aqui para realizar o cadastro!   </button>
    </a>
    </center>
  </div>
</div>
</div>
<script src="http://code.jquery.com/jquery-latest.js"></script><script src="js/bootstrap.min.js"></script>
</body>
</html>

alertageral/alerta/templates/confirmaenviaalerta.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sistema Alerta Geral</title>
<!--<link href="css/estilos.css" rel="stylesheet" type="text/css" />-->
<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body bgcolor="#dfeae2">
<div id="conteudo_principal">
<div id="banner"> </div>
  <div id="centro">
  <div id="centroform">
    <p><br />
      <br />
      <br />
      <h5>
      <font face="Arial, Helvetica, sans-serif"><b>Alerta  enviado com sucesso!</b></font>
      </h1>
      <br />
      <h6>
      </p>
    <p>
      </h1>
      <br />
      <br />
      <a href="login.html">
      </a></p>
    <a href="/">
    <button class="btn btn-danger" type="button">   Volta a tela inicial  </button>
    </a>    <a href="login.html">
    </a>  </div> 
  </div> 
  <div id="rodape">
  <br />
  <br />
  <center><h1><font face="Segoe Script">Novo no Alerta Geral?</font></h1></center>
  <center>
    <a href="cadastro.html">
    <button class="btn btn-danger" type="button">   Clique aqui para realizar o cadastro!   </button>
    </a>
    </center>
  </div>
</div>
</div>
<script src="http://code.jquery.com/jquery-latest.js"></script><script src="js/bootstrap.min.js"></script>
</body>
</html>

alertageral/alerta/templates/loginchave.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sistema Alerta Geral</title>
<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body bgcolor="#dfeae2">
<div id="conteudo_principal">
<div id="banner"> </div>
  <br>
    <div id="centro">
    <br><br>
        <br>
        <br>
        <br>
        <div id="centroform">
        {% if form.errors and not form.non_field_errors and not form.this_is_the_login_form.errors %}
            <p class="centro">
                {% blocktrans count form.errors.items|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
            </p>
        {% endif %}
    {% if erro %}
        <h5><font face="Arial, Helvetica, sans-serif" color=red>{{ erro }} Caracteres Maiusculos e Minusculos Fazem diferença caso o erro
		persista entre em contato com a administração do site ou departamento.</font></h5>
    {% endif %}
            <form action="/alerta/validar_responder_alerta/{{alerta.id}}" method="post" id="validar_responder_alerta_form">{% csrf_token %}
                    <br>
                    <br>
                    <span class="add-on"><i class="icon-qrcode"></i></span>
                    <input class="span2" name="chave" id="id_chave" type="password" placeholder="Chave de acesso">
                    <input type="hidden" name="this_is_the_login_form" value="1" />
                    <input type="hidden" name="next" value="{{ next }}" />
                <div align="center">
                <button class="btn btn-danger" type="submit">   Confirmar   </button>
                </div>

            </form>
            <script type="text/javascript">
                document.getElementById('id_username').focus();
            </script>

    </div>
    
</body>
</html>